name: CI

on:
  push:
    branches: [ "main", "*stable", "wip/*" ]
  pull_request:
    branches: [ "main", "*stable", "wip/*" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  NVIM_GTK_LOG_FILE: nvim-gtk-stdout.log
  NVIM_GTK_LOG_LEVEL: debug
  NVIM_GTK_STDERR: nvim-gtk-stderr.log
  RUSTFLAGS: -C opt-level=0

jobs:
  main:
    runs-on: [ubuntu-latest]
    container:
      image: fedora:37

    strategy:
      fail-fast: false
      matrix:
        # TODO: Windows, most of the instructions for this should be in ./appveyor.yml from
        # a5dd25c31ef03b47e87e68225a04d4b7852d9e09~1
        # TODO: OSX, this should be a bit easier hopefully
        os: [ubuntu-latest]
        rust: [stable]
        include:
          - os: ubuntu-latest
            rust: stable

    steps:
      - uses: actions/checkout@v3

      - name: Run dnf update
        run: dnf update -y

      - name: Install dependencies
        run: |
          dnf install -y --nodocs --setopt=install_weak_deps=False rust cargo rustfmt clippy atk-devel glib2-devel pango-devel gtk4-devel

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo test
        run: cargo test --locked

      - name: Check that rust-fmt is happy
        run: cargo fmt --check -v

      - name: Check for clippy lints
        run: cargo clippy -- -Dwarnings
